version: '3.5'

services:
  bdm.lambda:
    image: ${DOCKER_REGISTRY-}bdmlambda
    container_name: "bdmapp"
    build:
      context: .
      dockerfile: BDM.Lambda/Dockerfile
    depends_on:
       - postgres_data
    environment: 
      DB_CONNECTION_STRING: "host=postgres;port=5432;database=postgres;username=admin;password=password"
    networks: 
      - api-dev

  postgres_data:
    image: postgres:latest
    ports:
      - "3306:5432"
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - api-dev

networks:
  api-dev:
    driver: bridge
    
